//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adherence.Api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdherenceResult
    {
        public int Id { get; set; }
        public int PlanNumber { get; set; }
        public System.DateTime ResultDate { get; set; }
        public decimal A1cResult { get; set; }
        public string PremiumAdjustment { get; set; }
        public string ResultType { get; set; }
        public Nullable<int> ControlBand { get; set; }
        public string A1cUnit { get; set; }
    
        public virtual Plan Plan { get; set; }
    }
}
