//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adherence.Api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plan()
        {
            this.AdherenceResults = new HashSet<AdherenceResult>();
        }
    
        public int PlanNumber { get; set; }
        public string LifeAssuredName { get; set; }
        public System.DateTime PolicyStartDate { get; set; }
        public Nullable<decimal> CurrentPremium { get; set; }
        public Nullable<decimal> CurrentReinsurance { get; set; }
        public Nullable<decimal> CurrentPremiumAdjustment { get; set; }
        public Nullable<decimal> CurrentReinsuranceAdjustment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdherenceResult> AdherenceResults { get; set; }
    }
}
